import { listItems, mapKeys, roll, wizardName } from '../app/utils'
import { newSpellName } from './SpellName'

export function newMagicItem(props) {
  const bootyDie = props.bootyDie;

  // type, baseValue, enchantments, uses
  const generateMagicItemMap = (props) => {
    const enchantmentRoll = roll(bootyDie).result;
    const enchantments = (enchantmentRoll > 0) ? enchantmentRoll : 1;

    let magicItemMap = {
      3: [newMiscellaneous, 5 * roll(bootyDie).result, enchantments, roll(`2${bootyDie}`).result],
      5: [enchantedScroll, 10, 1, 1],
      8: [newPotion, 10, 1, 1],
      10: [newGarb, 2 * roll(`2${bootyDie}`).result, enchantments, roll(`2${bootyDie}`).result],
      12: [enchantedJewelry, 5 * roll(`2${bootyDie}`).result, enchantments, roll(`2${bootyDie}`).result],
      14: [newWandStaffRod, 20, enchantments, 2 * roll(bootyDie).result],
      17: [newWeapon, 'market value x 5', enchantments, roll(`2${bootyDie}`).result],
      20: [newArmorShield, 'market value x 5', enchantments, roll(`2${bootyDie}`).result],
    }
    return (magicItemMap);
  }
  const magicItemMap = generateMagicItemMap();
  const [category, baseValue, enchantments, uses] = magicItemMap[mapKeys(magicItemMap, roll('d20').result)];
  const type = category();

  // scrolls don't go through the naming template
  const name = (category.name === 'enchantedScroll') ? type : newMagicItemName(type);
  const magicItem = `${name} with ${enchantments} enchantments, ${uses} uses, worth ${baseValue} sp`

  return magicItem;
}

export function enchantedScroll() {
  const spell = newSpellName();
  return (`${spell}, a scroll`);
}

export function newPotion() {
  const potionMap = {
    2: 'Balm',
    4: 'Brew',
    9: 'Dust',
    24: 'Elixir',
    26: 'Glue',
    36: 'Oil',
    38: 'Ointment',
    40: 'Philter',
    42: 'Potation',
    73: 'Potion',
    78: 'Powder',
    88: 'Salve',
    90: 'Sap',
    92: 'Solution',
    94: 'Tincture',
    96: 'Tonic',
    100: 'Unguent',
  }
  const potion = potionMap[mapKeys(potionMap, roll('d100').result)];
  return potion;
}

export function newMiscellaneous() {
  const miscMap = {
    1: 'Bag',
    2: 'Banner',
    3: 'Barrel',
    4: 'Bed',
    5: 'Blanket',
    6: 'Boat',
    7: 'Book',
    8: 'Bottle',
    9: 'Bowl',
    10: 'Box',
    11: 'Bucket',
    12: 'Cabinet',
    13: 'Candle',
    14: 'Carpet',
    15: 'Case',
    16: 'Cauldron',
    17: 'Chain',
    18: 'Chair',
    19: 'Charm',
    20: 'Chest',
    21: 'Claw',
    22: 'Coffer',
    23: 'Cup',
    24: 'Cushion',
    25: 'Decanter',
    26: 'Drum',
    27: 'Ewer',
    28: 'Fang',
    29: 'Finger',
    30: 'Flag',
    31: 'Flagon',
    32: 'Flask',
    33: 'Flute',
    34: 'Fork',
    35: 'Gem',
    36: 'Glass',
    37: 'Glyph',
    38: 'Goblet',
    39: 'Golem',
    40: 'Gong',
    41: 'Hand',
    42: 'Harp',
    43: 'Head',
    44: 'Heart',
    45: 'Hook',
    46: 'Horn',
    47: 'Hourglass',
    48: 'Jewel',
    49: 'Jug',
    50: 'Kettle',
    51: 'Key',
    52: 'Lamp',
    53: 'Lantern',
    54: 'Light',
    55: 'Lock',
    56: 'Looking Glass',
    57: 'Lute',
    58: 'Lyre',
    59: 'Manacles',
    60: 'Map',
    61: 'Mark',
    62: 'Mirror',
    63: 'Net',
    64: 'Orb',
    65: 'Phial',
    66: 'Pillow',
    67: 'Pipes',
    68: 'Pitchfork',
    69: 'Pot',
    70: 'Pouch',
    71: 'Purse',
    72: 'Quill',
    73: 'Quilt',
    74: 'Rope',
    75: 'Rug',
    76: 'Rune',
    77: 'Sack',
    78: 'Scabbard',
    79: 'Shard',
    80: 'Sheath',
    81: 'Ship',
    82: 'Sigil',
    83: 'Skull',
    84: 'Sphere',
    85: 'Splinter',
    86: 'Spoon',
    87: 'Steed',
    88: 'Stone',
    89: 'Sundial',
    90: 'Symbol',
    91: 'Throne',
    92: 'Tome',
    93: 'Tool',
    94: 'Tooth',
    95: 'Totem',
    96: 'Urn',
    97: 'Vase',
    98: 'Well',
    99: 'Wine',
    100: 'Yoke',
  }
  const miscellaneous = miscMap[mapKeys(miscMap, roll('d100').result)];
  return miscellaneous;
}

export function newGarb() {
  const garbMap = {
    1: 'Apron',
    2: 'Band',
    12: 'Belt',
    13: 'Blouse',
    23: 'Boots',
    28: 'Cap',
    33: 'Cape',
    45: 'Cloak',
    46: 'Coat',
    47: 'Cowl',
    48: 'Dress',
    49: 'Garb',
    50: 'Garment',
    51: 'Girdle',
    61: 'Glove(s)',
    62: 'Gown',
    63: 'Hat',
    64: 'Hood',
    65: 'Jacket',
    66: 'Jerkin',
    67: 'Mantle',
    68: 'Mask',
    69: 'Raiment',
    79: 'Robe',
    80: 'Sandals',
    81: 'Sash',
    82: 'Scarf',
    83: 'Shawl',
    88: 'Shoes',
    89: 'Skirt',
    93: 'Slippers',
    94: 'Surcoat',
    95: 'Trews',
    96: 'Trousers',
    97: 'Tunic',
    98: 'Veil',
    99: 'Vestment',
    100: 'Wrap',
  }
  const garb = garbMap[mapKeys(garbMap, roll('d100').result)];
  return garb;
}

export function enchantedJewelry() {
  const jewelryMap = {
    10: 'Amulet',
    11: 'Anklet',
    12: 'Armband',
    13: 'Armlet',
    18: 'Band',
    19: 'Bangle',
    20: 'Bauble',
    25: 'Bracelet',
    26: 'Brooch',
    27: 'Buckle',
    28: 'Charm',
    29: 'Choker',
    30: 'Circlet',
    31: 'Collar',
    36: 'Crown',
    37: 'Diadem',
    38: 'Earrings',
    39: 'Figurine',
    40: 'Fillet',
    41: 'Garland',
    42: 'Gorget',
    43: 'Headband',
    44: 'Icon',
    45: 'Idol',
    46: 'Locket',
    47: 'Loop',
    48: 'Medallion',
    59: 'Necklace',
    60: 'Nosering',
    61: 'Ornament',
    62: 'Pendant',
    63: 'Pin',
    64: 'Prize',
    65: 'Regalia',
    95: 'Ring',
    96: 'Signet',
    97: 'Talisman',
    98: 'Tiara',
    99: 'Treasure',
    100: 'Trinket',
  }
  const jewelry = jewelryMap[mapKeys(jewelryMap, roll('d100').result)];
  return jewelry;
}

export function newWandStaffRod() {
  const staffMap = {
    5: 'Baton',
    10: 'Cane',
    15: 'Crook',
    30: 'Rod',
    40: 'Scepter',
    70: 'Staff',
    75: 'Stick',
    100: 'Wand',
  }
  const staff = staffMap[mapKeys(staffMap, roll('d100').result)];
  return staff;
}

export function newWeapon() {
  const weaponMap = {
    1: 'Ally',
    2: 'Arrow(s)',
    7: 'Axe',
    8: 'Bane',
    9: 'Battle Axe',
    14: 'Blade',
    15: 'Bludgeon',
    16: 'Bolt(s)',
    21: 'Bow',
    22: 'Brand',
    23: 'Club',
    24: 'Companion',
    25: 'Crossbow',
    26: 'Cudgel',
    27: 'Curse',
    32: 'Dagger',
    33: 'Dart(s)',
    34: 'Edge',
    35: 'Flail',
    36: 'Friend',
    37: 'Glaive',
    38: 'Great Axe',
    39: 'Great Hammer',
    40: 'Great Sword',
    41: 'Halberd',
    46: 'Hammer',
    47: 'Hatchet',
    48: 'Javelin',
    53: 'Knife',
    54: 'Lance',
    55: 'Longaxe',
    56: 'Longbow',
    57: 'Longsword',
    62: 'Mace',
    63: 'Maul',
    64: 'Morning Star',
    65: 'Nail',
    66: 'Pick',
    67: 'Pike',
    68: 'Quarterstaff',
    69: 'Saber',
    70: 'Scourge',
    71: 'Shortbow',
    76: 'Shortsword',
    77: 'Sling',
    78: 'Sparth',
    83: 'Spear',
    84: 'Spike',
    99: 'Sword',
    100: 'Warhammer',
  }
  const weapon = weaponMap[mapKeys(weaponMap, roll('d100').result)];
  return weapon;
}

export function newArmorShield() {
  const armorMap = {
    1: 'Aegis',
    2: 'Bastion',
    12: 'Bracers',
    13: 'Breastplate',
    18: 'Buckler',
    23: 'Chainmail',
    24: 'Defense',
    34: 'Gauntlets',
    35: 'Greaves',
    36: 'Guard',
    46: 'Helm',
    51: 'Helmet',
    52: 'Iron',
    62: 'Leather',
    69: 'Mail',
    70: 'Plate',
    75: 'Scale',
    76: 'Shell',
    94: 'Shield',
    95: 'Skin',
    96: 'Steel',
    97: 'Vambraces',
    98: 'Visor',
    99: 'Wall',
    100: 'Ward',
  }
  const armor = armorMap[mapKeys(armorMap, roll('d100').result)];
  return armor;
}

function newMagicItemName(item) {
  const magicPropertyAdjectiveMap = {
    1: ['Air', 'Accursed'],
    2: ['Alacrity', 'All-Seeing'],
    3: ['Autumn', 'Arcane'],
    4: ['Beast', 'Befuddling'],
    5: ['Blood', 'Binding'],
    6: ['Bone', 'Bitter'],
    7: ['Calamity', 'Black'],
    8: ['Charm', 'Blazing'],
    9: ['Agility', 'Blessed'],
    10: ['Control', 'Blinding'],
    11: ['Cosmos', 'Bright'],
    12: ['Darkness', 'Broken'],
    13: ['Death', 'Burning'],
    14: ['Defense', 'Capacious'],
    15: ['Deflection', 'Cerulean'],
    16: ['Destruction', 'Concealing'],
    17: ['Dominance', 'Confusing'],
    18: ['Earth', 'Consuming'],
    19: ['Envy', 'Crimson'],
    20: ['Fire', 'Dark'],
    21: ['Flight', 'Dazzling'],
    22: ['Foe', 'Deafening'],
    23: ['Force', 'Delicate'],
    24: ['Fortitude', 'Demonic'],
    25: ['Fortune', 'Devastating'],
    26: ['Fury', 'Devilish'],
    27: ['Glory', 'Dim'],
    28: ['Gluttony', 'Draining'],
    29: ['Grace', 'Dwarven'],
    30: ['Greed', 'Eldritch'],
    31: ['Hand', 'Elvish'],
    32: ['Hate', 'Empowering'],
    33: ['Healing', 'Enlightening'],
    34: ['Health', 'Ensorcelling'],
    35: ['Heart', 'Entangling'],
    36: ['Heroism', 'Enveloping'],
    37: ['Humility', 'Excruciating'],
    38: ['Ice', 'Extra-Planar'],
    39: ['Ineptitude', 'Fearsome'],
    40: ['Insight', 'Flaming'],
    41: ['Intellect', 'Floating'],
    42: ['Invocation', 'Frozen'],
    43: ['Invulnerability', 'Glittering'],
    44: ['Judgement', 'Healing'],
    45: ['Levitation', 'Hindering'],
    46: ['Life', 'Icy'],
    47: ['Light', 'Illusory'],
    48: ['Love', 'Ingenious'],
    49: ['Luck', 'Instant'],
    50: ['Magic', 'Invigorating'],
    51: ['Mercy', 'Invisible'],
    52: ['Might', 'Invulnerable'],
    53: ['Mistake', 'Iron'],
    54: ['Moon', 'Irresistible'],
    55: ['Mountain', 'Liberating'],
    56: ['Necromancy', 'Lordly'],
    57: ['Night', 'Maddening'],
    58: ['Patience', 'Magnificent'],
    59: ['Poison', 'Many-Colored'],
    60: ['Power', 'Mighty'],
    61: ['Pride', 'Most Excellent'],
    62: ['Puissance', 'Oozing'],
    63: ['Resistance', 'Piercing'],
    64: ['River', 'Poisonous'],
    65: ['Sacrifice', 'Prismatic'],
    66: ['Sea', 'Radiant'],
    67: ['Shadow', 'Red'],
    68: ['Sight', 'Rejuvenating'],
    69: ['Silence', 'Restorative'],
    70: ['Sloth', 'Scintillating'],
    71: ['Song', 'Screaming'],
    72: ['Sorcery', 'Shimmering'],
    73: ['Soul', 'Shining'],
    74: ['Speed', 'Shivering'],
    75: ['Spring', 'Sleeping'],
    76: ['Stars', 'Slow'],
    77: ['Stone', 'Splintered'],
    78: ['Storm', 'Strange'],
    79: ['Strength', 'Stupefying'],
    80: ['Stride', 'Terrible'],
    81: ['Submission', 'Thirsty'],
    82: ['Summer', 'Thundering'],
    83: ['Summoning', 'Transforming'],
    84: ['Sun', 'Uncontrollable'],
    85: ['Swimming', 'Unseen'],
    86: ['Thunder', 'Unstoppable'],
    87: ['Trickery', 'Untiring'],
    88: ['Venom', 'Vengeful'],
    89: ['Voice', 'Vexing'],
    90: ['Void', 'Violent'],
    91: ['Vulnerability', 'Violet'],
    92: ['Warding', 'Viridian'],
    93: ['Water', 'Weakening'],
    94: ['Weakness', 'White'],
    95: ['Wind', 'Wondrous'],
    96: ['Winter', 'Yellow'],
    97: ['Wisdom', 'Weakening'],
    98: ['Word', 'White'],
    99: ['Wrath', 'Wondrous'],
    100: ['Zeal', 'Yellow'],
  }
  const property = magicPropertyAdjectiveMap[mapKeys(magicPropertyAdjectiveMap, roll('d100').result)][0];
  const adjective = magicPropertyAdjectiveMap[mapKeys(magicPropertyAdjectiveMap, roll('d100').result)][1];

  const magicItemNameTemplates = {
    2: `The ${property} ${item}`,
    4: `The ${adjective} ${item}`,
    6: `The ${item} of ${property}`,
    8: `The ${adjective} ${item} of ${property}`,
    9: `${wizardName()}'s ${item}`,
    10: `${wizardName()}'s ${item} of ${property}`,
    11: `${wizardName()}'s ${adjective} ${item}`,
    12: `${wizardName()}'s ${property} ${item}`,
  }
  const magicItemName = magicItemNameTemplates[mapKeys(magicItemNameTemplates, roll('d12').result)];

  return magicItemName;
}

export default function magicItem(props) {
  return (listItems(props, newMagicItem));
}